[video]
out = "video.mp4"
overwrite = true

[source]
background = "assets/background.mp4"
watermark = "awesome!"

[reddit]
# subreddit = "askreddit"
sort = "top"
time = "month"
# comments = true
limit = 50

