#!/bin/sh

out='assets/out/final.mp4'

if test -f $out; then
  rm $out
fi

cargo run &&

if test -f $out; then
  echo "Press ENTER to start video..."
  read
  nohup xdg-open $out > /dev/null
else
  echo "Error: Output file was not created"
fi

